"use client";
import { createClient } from "@supabase/supabase-js";
import { useEffect, useState } from "react";
const ready = Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
const client = ready ? createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!) : null;
type Overview = { configured: boolean; metrics: { destinations:number; users:number; trips:number; generations:number }; events: { event_type:string; status:string; provider?:string; created_at:string }[] };
export default function AdminDashboard(){
  const [overview,setOverview]=useState<Overview|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const request=async(path:string, options:RequestInit={})=>{if(!client) throw new Error("Supabase is not configured.");const {data:{session}}=await client.auth.getSession();if(!session) throw new Error("Please sign in first.");const r=await fetch(path,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`,...options.headers}});const json=await r.json().catch(()=>({}));if(!r.ok)throw new Error(json.error||"Request failed.");return json;};
  const load=async()=>{try{setError("");setOverview(await request("/api/admin/overview"));}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard.")}};
  useEffect(()=>{if(ready)load()},[]);
  const seed=async()=>{try{setBusy(true);const data=await request("/api/admin/destinations/seed",{method:"POST"});await load();alert(`Seeded ${data.seeded} destinations.`)}catch(e){setError(e instanceof Error?e.message:"Seed failed.")}finally{setBusy(false)}};
  return <main className="admin"><a href="/">← Back to planner</a><p className="eyebrow">OPERATIONS DASHBOARD</p><h1>Trip planner API</h1>{!ready?<section><h2>Supabase is not configured</h2><p>Add the Supabase values from <code>.env.example</code>, restart the app, and sign in with an email listed in <code>ADMIN_EMAILS</code>.</p></section>:error?<section><h2>Access required</h2><p>{error}</p><a href="/login">Sign in →</a><br/><a href="/signup">Create account →</a></section>:overview?<><div className="metrics"><article><b>{overview.metrics.destinations}</b><span>Saved destinations</span></article><article><b>{overview.metrics.trips}</b><span>Saved trips</span></article><article><b>{overview.metrics.generations}</b><span>Recorded requests</span></article></div><section><h2>Destination database</h2><p>Load the bundled Manipur destinations into Supabase once. Re-running this is safe and updates matching IDs.</p><button onClick={seed} disabled={busy}>{busy?"Seeding…":"Seed destination data"}</button></section><section><h2>Recent activity</h2>{overview.events.length?<ul>{overview.events.map((event,i)=><li key={i}>{event.event_type.replaceAll("_"," ")} · {event.status} <small>{new Date(event.created_at).toLocaleString()}</small></li>)}</ul>:<p>No events yet. Generate a trip to see activity here.</p>}</section><section><h2>Endpoints</h2><code>GET /api/health</code><code>GET /api/destinations</code><code>POST /api/itinerary</code><code>GET, POST /api/trips</code></section></>:null}</main>;
}
